In [1]:
import sys
import numpy as np
import pandas as pd
import os
sys.path.append('..')
print(sys.path)
from nlp_pipeline.feature_extraction import FeatureExtractor
from nlp_pipeline.preprocess_text import TextPreprocessor
from model.evaluate_model import ModelEvaluator
from model.train_baseline import BaselineTrainer
from interpretation.lime_interpreter import LimeTextInterpreter

['/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '', '/hop/home/muhammad_mufli_ramadhan/tfid/lib/python3.8/site-packages', '..']


/hop/home/muhammad_mufli_ramadhan/tfid/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Load dataset

In [2]:
df = pd.read_csv('../data/features/1.csv', encoding='latin1')
print(df.columns)
df['label'] = df['label'].astype(str)
df['label'].value_counts()
df['label'].value_counts()

Index(['interaction_control', 'target_of_utterance', 'seg_id', 'vid_id',
       'start_time', 'end_time', 'speaker_id', 'role', 'label',
       'transcription', 'duration', 'utterance_type', 'annotation',
       'valid_segment', 'total_words', 'unique_words', 'num_sentences',
       'stopwords', 'num_adjectives', 'num_nouns', 'num_verbs', 'num_adverbs',
       'type_token_ratio', 'avg_words_per_sentence', 'soruce_file'],
      dtype='object')


label
NON ASD    2324
ASD        1244
Name: count, dtype: int64

Preprocessing text

In [3]:
text_preprocessor = TextPreprocessor()
df['clean_text'] = df['transcription'].apply(text_preprocessor.preprocess)
df[['transcription', 'clean_text']].head()

transcription        clean_text
0  Tunjuk kaka coba  tunjuk kaka coba
1             Inii!               ini
2     Siapa namamu?        siapa nama
3           Iyaaaa?                  
4    Kenalan duluu!       kenal duluu

Ekstraksi fitur

In [4]:
extractor = FeatureExtractor()
X = extractor.fit_transform_tfidf(df['clean_text'])
y = df['label'].values
print(X.shape, y.shape)

(3568, 4437) (3568,)


SVC WITH 5 FOLD

In [5]:
trainer = BaselineTrainer()
evaluator = ModelEvaluator(model_type='svm')

results = evaluator.cross_validate(X,y)


Fold 1
              precision    recall  f1-score   support

         ASD      0.677     0.775     0.723       249
     NON ASD      0.869     0.802     0.834       465

    accuracy                          0.793       714
   macro avg      0.773     0.789     0.779       714
weighted avg      0.802     0.793     0.796       714

Confusion Matrix:
 [[193  56]
 [ 92 373]]

Fold 2
              precision    recall  f1-score   support

         ASD      0.710     0.719     0.715       249
     NON ASD      0.848     0.843     0.846       465

    accuracy                          0.800       714
   macro avg      0.779     0.781     0.780       714
weighted avg      0.800     0.800     0.800       714

Confusion Matrix:
 [[179  70]
 [ 73 392]]

Fold 3
              precision    recall  f1-score   support

         ASD      0.731     0.795     0.762       249
     NON ASD      0.885     0.843     0.863       465

    accuracy                          0.826       714
   macro avg      0.

LINEAR REGRETION WITH 5 FOLD

In [6]:
trainer = BaselineTrainer()
evaluator = ModelEvaluator()

results = evaluator.cross_validate(X,y)


Fold 1
              precision    recall  f1-score   support

         ASD      0.792     0.337     0.473       249
     NON ASD      0.729     0.953     0.826       465

    accuracy                          0.738       714
   macro avg      0.761     0.645     0.649       714
weighted avg      0.751     0.738     0.703       714

Confusion Matrix:
 [[ 84 165]
 [ 22 443]]

Fold 2
              precision    recall  f1-score   support

         ASD      0.783     0.289     0.422       249
     NON ASD      0.715     0.957     0.819       465

    accuracy                          0.724       714
   macro avg      0.749     0.623     0.621       714
weighted avg      0.739     0.724     0.680       714

Confusion Matrix:
 [[ 72 177]
 [ 20 445]]

Fold 3
              precision    recall  f1-score   support

         ASD      0.812     0.329     0.469       249
     NON ASD      0.728     0.959     0.827       465

    accuracy                          0.739       714
   macro avg      0.

SVM WITH 10 FOLD

In [ ]:
trainer = BaselineTrainer()
evaluator = ModelEvaluator(model_type='svm', n_splits= 10, random_state=32)

results = evaluator.cross_validate(X,y)